[package]
name = "avmir"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.4"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'
